name: system_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.3
  intl: ^0.19.0
  rename: ^3.0.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
dev_dependencies:
  build_runner: "^2.4.14"
  custom_lint: "^0.7.0"
  custom_lint_builder: "^0.7.0"
  flutter_gen_runner: "^5.10.0"
  flutter_lints: "^5.0.0"
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: "^1.0.5"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
flutter_intl:
  enabled: true

