require 'dotenv'

# ✅ تحميل متغيرات البيئة من .env في جذر المشروع
env_path = File.expand_path("../../../.env", __FILE__)
Dotenv.load(env_path) if File.exist?(env_path)

default_platform(:android)

platform :android do
  desc "🚀 Distribute APK to Firebase with Fastlane"

  lane :firebase_distribution do
    # 🧹 تنظيف المشروع قبل البناء
    sh "flutter clean"

    # 🏗️ بناء نسخة الإصدار بصيغة APK
    sh "flutter build apk --release --no-tree-shake-icons"

    # 🚀 توزيع النسخة عبر Firebase App Distribution
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: ENV["FIREBASE_TESTERS"],
      release_notes: ENV["FIREBASE_RELEASE_NOTES"]
    )
  end
end